SELECT * FROM location;
SELECT * FROM station;
SELECT * FROM measurement;
SELECT * FROM plan;
SELECT * FROM finaluser;
SELECT * FROM administrator;
SELECT * FROM client;
SELECT * FROM apikey;
SELECT * FROM queryhistory;